version: '3.3'
services:
  db:
    container_name: pets_db
    image: library/postgres:${POSTGRES_VERSION}

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=pets
      - PGDATA=/var/lib/postgresql/data/pets
    ports:
      - 5433:5432

  test_db:
    container_name: test_pets_db
    image: library/postgres:${POSTGRES_VERSION}

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=test_pets
      - PGDATA=/var/lib/postgresql/data/test_pets
    ports:
    - 5434:5432